---
# Password-based tasks (first run)

- name: Check if SSH key pair already exists
  ansible.builtin.stat:
    path: "{{ ssh_key_path }}"
  register: key_stat
  delegate_to: localhost # Run on the control node
  become: false

- name: Generate SSH key pair, if it is need
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: ed25519
  when: not key_stat.stat.exists
  register: ssh_key # Save generated key in variable
  delegate_to: localhost
  become: false

- name: Read public key (from register or file)
  set_fact:
    deploy_public_key: >-
      {% if ssh_key is defined and ssh_key.changed %}
        {{ ssh_key.public_key }}
      {% else %}
        {{ lookup('file', ssh_key_path ~ '.pub') }}
      {% endif %}
    delegate_to: localhost
    become: false

- name: Ensure deploy user exists
  user:
    name: "{{ deploy_user }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Set authorized key
  ansible.posix.authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ deploy_public_key }}"
    state: present

- name: Allow passwordless sudo
  copy:
    content: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/{{ deploy_user }}
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s

- name: Disable password-based auth (Ubuntu)  
  copy:
    dest: /etc/ssh/sshd_config.d/00-disable-password-login.conf
    content: PasswordAuthentication no
    mode: '0600'
    
- name: Reload SSH service
  systemd:
    name: ssh
    state: reloaded

- name: Check password is disabled
  shell: sshd -T | grep "passwordauthentication"
  register: command_checkpass

- name: Stop if password login is still enabled
  fail:
    msg: "Error! Cannot disable password-based auth"
  when: "'yes' in command_checkpass"

...